name:                 lumenscript-studio
version:              0.1.0.0
visibility:           public
id:                   lumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g
key:                  lumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g
license:              BSD-3-Clause
maintainer:           your.email@example.com
author:               Your Team
abi:                  65163609b3fecf0a47d192595af161a7
exposed:              True
exposed-modules:
    AST Bytecode.Generator Bytecode.Instruction GUI.ASTViewer
    GUI.BytecodeViewer GUI.EditorPanel GUI.StackTraceViewer
    GUI.TokenViewer HostBindings Lexer Parser Semantic.ErrorLog
    Semantic.ScopeResolution Semantic.SymbolTable Semantic.TypeCheck
    Simulation.GridWorld Simulation.SimState Token VM.EventTrigger
    VM.Stack VM.VM

import-dirs:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\lib\x86_64-windows-ghc-9.6.6\lumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g

library-dirs:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\lib\x86_64-windows-ghc-9.6.6\lumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

library-dirs-static:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\lib\x86_64-windows-ghc-9.6.6\lumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

dynamic-library-dirs:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\lib\x86_64-windows-ghc-9.6.6
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

data-dir:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\share\x86_64-windows-ghc-9.6.6\lumenscript-studio-0.1.0.0

hs-libraries:         HSlumenscript-studio-0.1.0.0-9ZAsUK9JWrqA2uwmmH3D5g
include-dirs:
    C:\Users\LENOVO\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\include

depends:
    aeson-2.1.2.1-74J0fcHiEUz1NUNJDAiNuG base-4.18.2.1 containers-0.6.7
    mtl-2.3.1 parsec-3.1.16.1 pretty-1.1.3.6 text-2.0.2
    threepenny-gui-0.9.4.1-GuzznOLvsNRA6fPpRDFj10 transformers-0.6.1.0
    vector-0.13.1.0-Aqc2YUE1Egs5WmXVMbcJ5T

haddock-interfaces:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\doc\lumenscript-studio-0.1.0.0\lumenscript-studio.haddock

haddock-html:
    C:\Users\LENOVO\OneDrive\Desktop\gamescript_studio\GameScript-Studio\lumenscript-studio\.stack-work\install\8a13d1de\doc\lumenscript-studio-0.1.0.0
